### PR TITLE
Fixed Windows 10 theme

### PR DESCRIPTION
**Pull request by veler**
## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [ ] New feature or enhancement
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

image

image

Issue Number: #1191

## What is the new behavior?

Not perfect but it addresses the emergency:

image

image

## Quality check

Before creating this PR:

- [X] Did you follow the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? On Windows, you can use Accessibility Insights for this.
- [ ] Did you verify that the change work in Release build configuration
- [ ] Did you verify that all unit tests pass
- [ ] If necessary and if possible, did you verify your changes on:
   - [X] Windows 10 & 11
   - [ ] macOS
   - [ ] Linux

### CODE REVIEW

**Comment by btiteux** [comment]
I just tested and I have an issue on Windows 11:
image

**Comment by veler** [comment]
> I just tested and I have an issue on Windows 11: image

I just checked and it already happening in 2.0.1, so it's not a regression introduced by this PR. Also, you're testing Windows 11 here. The fix I'm doing specifically targets Windows 10.

image

I opened an issue for it here: https://github.com/DevToys-app/DevToys/issues/1228

I will try to take look at it ASAP :)

**Comment by btiteux** [comment]
I hadn't seen this issue before, so I was not sure. I think for Windows 10 it should be ok, I don't have a Windows 10 VM to test it.

**Review by btiteux — APPROVED** [review]

**Comment by Brent-Sanchez** [comment]
!!!!
I thought it was just me!  
https://github.com/microsoft/PowerToys/issues/33385
+==================================================+
The screenshots below are to show my current "accent" color (Morocco Sand colored title bar, explorer window)
It doesn't match the previous accent color that remained in PowerToys (369% saturation highlighter blue)  This is without a restart.
image
image
+-----------------------------------------------------+
I might just be a dumb n00b, but my suspicion is that PowerToys and DevToys aren't playing nice together.  One or the other tends to crash if both are active on the screen.  So as I screwed around this more, I crashed PowerToys, and you might be able to predict what I'm going to say next.  
The issue stopped.  Since I didn't crash it on purpose, it took until until I started PowerToys back up to realize this for blidingly obvoius reasons.  PowerToys resumed it's behavior from the officially released build, without any accented title bar.  
I hope this helps you out!  🐱‍👓  
~�~

**Comment by veler** [comment]
Hi,
Did you update do devtoys 2.0.2.0? The issue must be fixed in this version now.
Thanks

**Pull request merged**
